### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by pptxman** [garrettrayj/auto-reload#1]
Hi Garret, I made an icon in the modern macOS style. If you like it let's replace the old one.
<img width="687" alt="Screenshot 2021-10-30 at 14 05 49" src="https://user-images.githubusercontent.com/44065778/139530493-e02eb624-4748-4a3f-8da2-974d4b51041e.png">

**Comment by garrettrayj** [comment]
I ABSOLUTELY LOVE IT! Beautiful work on the bezel highlight!

If you'd like credit for the icon on the about screen or somewhere in the start app I'd be happy to oblige.

**Comment by pptxman** [comment]
Cool! Credits like this would be great:
<img width="318" alt="Group 1" src="https://user-images.githubusercontent.com/44065778/139845328-a3fc7027-c504-45b4-89f4-696323f47e91.png">

**Comment by pptxman** [comment]
The icon itself
[Auto Reload.icns.zip](https://github.com/garrettrayj/auto-reload/files/7460550/Auto.Reload.icns.zip)
