### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by pptxman** [garrettrayj/auto-reload#2]
Timer looks strange on macOS Monterey 12.0.1 with Safari 15.1 (17612.2.9.1.20
![Screen Recording 2021-10-30 at 14 22 25](https://user-images.githubusercontent.com/44065778/139532137-49bb565e-a931-4e8e-a58c-e504111db206.gif)
)

**Comment by garrettrayj** [comment]
Thank you for reporting. This is my first weekend with Monterey out and will be giving the extension a debug pass first thing.

Sorry I'm late to the party, fixes are on the way.
