### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by ljharb** [garrettrayj/auto-reload#3]
I installed this, and it seems like it only reloads the active tab in the current window - meaning, if i switch tabs, the previous one is not reloaded and the new one is.

Since the setting is window-wide I would have assumed it applies to *every* tab in the window, active or not. Is there a way to get this functionality?

**Comment by garrettrayj** [comment]
If you're willing to compile yourself then the code hack would be switching out `getActiveTab` with `getAllTabs` in [Reloader.swift](https://github.com/garrettrayj/auto-reload/blob/103197513750eea7010c6d4d9f02b1dddf29a810/SafariExtension/Reloader.swift#L25).

I do like the idea of adding a proper option to the extension though. Not only would it be useful to have, but a toggle for active vs. all might help clear up some confusion on what's reloading. You're not the only one who's assumed it would work different.

Let me test it and think on the UI some. Stay tuned...

**Comment by ljharb** [comment]
Awesome, thanks :-)

**Comment by garrettrayj** [comment]
It works! Here's what I came up with for UI. I'm getting a few other things knocked out then plan on shipping in the next day or so.

<img width="182" alt="Screenshot 2023-09-01 at 10 56 21 AM" src="https://github.com/garrettrayj/auto-reload/assets/1203214/164bff66-ea6d-4865-99ec-086d109f826e">

**Comment by ljharb** [comment]
That sounds great! It'd also be nice to have tab-specific settings instead of just "active tab" - ie, make it a three-way switch with "This Tab" so i can have individual tabs with different reload periods, and some off entirely.

**Comment by garrettrayj** [comment]
That's similar to how version 1.x worked. Individual tabs were the focus of reloaders. Unfortunately I wasn't able to make it entirely stable, so I changed it to windows being the main focus. It was a case of either I was doing it wrong or Apple never intending for me to abuse the API like I was. Either way, I don't plan on revisiting it. 

I haven't kept up with them, but perhaps one of the other Safari refresh apps would fit your use-case better. It would be much easier to implement in a JavaScript based extension, but "no extra scripts or permissions" is this project's motto.

**Comment by ljharb** [comment]
Understood. I'll take a look at the others too, but either way I think this is already an improvement here :-)

**Comment by garrettrayj** [comment]
Active/all tabs scope toggle released in 2.1.0
