### ISSUE TITLE
Hotkeys for start/stop

### ISSUE THREAD

**Issue by kiprusov** [garrettrayj/auto-reload#4]
Hi!

Is there is any possibility to use hotkeys to turn on/off the reload? As I need to constantly update a page for new items and if the item shows, I need to manually turn off the reload as I need to observe this item a little bit more. 

And it would be also great to have not an active tab but the dedicated tab to be updated - no matter if it's active or not. 

Thanks!

**Comment by Moulaythami** [comment]
Hi @garrettrayj 
I agree, it would be dope to have the extension only reloading a defined tab!
Cheers.

**Comment by garrettrayj** [comment]
I'm not seeing a way to add hotkey support to the extension directly, but it may be possible with AppleScript. [This StackExchange answer](https://apple.stackexchange.com/questions/296440/assign-keyboard-shortcut-to-safari-extensions) looks like a good starting point.

Version 1.x worked with individual tabs but I couldn't make it entirely reliable. It's either that the extension API doesn't support it, or more likely, I was doing something wrong. Either way, I don't plan on revisiting it.
